name: Setup Environment
description: Sets up development dependencies needed to build and test YTAF.

inputs:
  node-version:
    description: 'Node.js version to set up'
    required: false
    default: 'lts/*'

runs:
  using: 'composite'

  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Set up Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install
      shell: bash
